name: Christian Repato
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15346
title: Christian Repato
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0c2233'
    - '#065471'
    - '#0a91ab'
    - '#ffc045'
    - '#f7ba43'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
