name: Christian Repato
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31206
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00142f'
    - '#196589'
    - '#61c1da'
    - '#ace6f2'
    - '#979548'
  brandStrength: 1
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.75
purpose: []
