typography_spectrum: 0.15346
color:
  brandColors:
    - '#0c2233'
    - '#065471'
    - '#0a91ab'
    - '#ffc045'
    - '#f7ba43'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Christian Repato
  email: emailme@christianrepato.com
  url: christianrepato.com
name: Christian Repato
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Christian Repato
purpose: []
