typography_spectrum: 0.15346
content_rating:
  adult: false
color:
  brandColors:
    - '#0c2233'
    - '#065471'
    - '#0a91ab'
    - '#ffc045'
    - '#f7ba43'
  brandStrength: 1
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Christian Repato
  email: emailme@christianrepato.com
  url: christianrepato.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1462f0c3-8e44-42ae-a03c-2eba1b181c84.png
name: Christian Repato
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Contact
    id: b64091ac-6717-4f79-96b0-33544bca12d1
    type: content
  - name: Title of another page
    id: 08742a86-8c7d-4c6a-b7e9-b16af5397866
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/82eaa7ba-56fd-4bee-86e9-42736d71b061.png
title: a designer
purpose: []
