name: Christian Repato
favicon: null
layout_spectrum: 0.6499925574753433
typography_spectrum: 0.2052157949656248
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.08322693151421845
  lightness: 0.7625220397021621
  saturation: 0.40876467945054173
  rhythmicContrast: 0.3459732346236706
purpose: []
