typography_spectrum: 0.9947725690435618
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.7177230992820114
  lightness: 0.6282925456762314
  saturation: 0.09738653805106878
  rhythmicContrast: 0.9629551195539534
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.03475496941246092
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Christian Repato
  email: emailme@christianrepato.com
  url: christianrepato.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1462f0c3-8e44-42ae-a03c-2eba1b181c84.png
name: Christian Repato
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: a designer
purpose: []
