typography_spectrum: 0.28665713127702475
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.07528864359483123
  lightness: 0.6252856587525457
  saturation: 0.7227966475766152
  rhythmicContrast: 0.1402543520089239
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8721408757846802
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Christian Repato
  email: emailme@christianrepato.com
  url: christianrepato.com
name: Christian Repato
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Christian Repato
purpose: []
