name: Christian Repato
favicon: null
layout_spectrum: 0.00083
typography_spectrum: 0.03493
title: Christian Repato
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060603'
    - '#636363'
    - '#f8f4f1'
    - '#a98471'
    - '#cecac7'
  brandStrength: 0.5
  lightness: 0.875
  saturation: 0.6875
  rhythmicContrast: 0.5
purpose: []
