typography_spectrum: 0.6836909821722656
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.9533942341804504
  lightness: 0.7088147848844528
  saturation: 0.9491785659920424
  rhythmicContrast: 0.7837168844416738
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.3903333554044366
analytics:
  google: null
  facebook: null
  twitter: null
author:
  name: Christian Repato
  email: emailme@christianrepato.com
  url: christianrepato.com
name: Christian Repato
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Christian Repato
purpose: []
