name: Christian Repato
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15346
title: Christian Repato
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#060603'
    - '#636363'
    - '#f8f4f1'
    - '#a98471'
    - '#cecac7'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
