name: Christian Repato
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31206
title: Christian Repato
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#00142f'
    - '#196589'
    - '#61c1da'
    - '#ace6f2'
    - '#979548'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
