name: Christian Repato
favicon: null
layout_spectrum: 1
typography_spectrum: 0.15346
title: Christian Repato
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0274bd'
    - '#909090'
    - '#333333'
    - '#02be94'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
